### ISSUE TITLE
May I have your package name? :)

### ISSUE THREAD

**Issue by mefellows** [dong-dohai/cypress-pact#1]
Hello!

I'm a maintainer of Pact, and would like to create a `cypress-pact` plugin - would you be open to transferring ownership of the package to the `pact-foundation`?

Thanks!
Matt

**Comment by dong-dohai** [comment]
np. what is your/pact-foundation npm account?

**Comment by mefellows** [comment]
Thanks so much 🙏! The namespace we publish under is `@pact-foundation` and a key user is `pact-foundation`. So perhaps just add to that user and we can go from there.

**Comment by dong-dohai** [comment]
it's done. I am keeping myself as a maintainer in case of any complication. but when you can confirm that you sorted it out. I will remove myself :)

**Comment by mefellows** [comment]
Awesome, thanks for that - I can see the package in the account. Much appreciated! (also if you are still using both Cypress and Pact, you may be interested in https://pactflow.io/blog/cypress-pact-front-end-testing-with-confidence/).

I'll be in touch over the next little while - the idea is to extract the code from that demo into a package.
